package birdwatcher

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *DBDump) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "adds":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "NetAddrs")
				return
			}
			if zb0002 != uint32(256) {
				err = msgp.ArrayError{Wanted: uint32(256), Got: zb0002}
				return
			}
			for za0001 := range z.NetAddrs {
				var zb0003 uint32
				zb0003, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "NetAddrs", za0001)
					return
				}
				if zb0003 != uint32(256) {
					err = msgp.ArrayError{Wanted: uint32(256), Got: zb0003}
					return
				}
				for za0002 := range z.NetAddrs[za0001] {
					var zb0004 uint32
					zb0004, err = dc.ReadArrayHeader()
					if err != nil {
						err = msgp.WrapError(err, "NetAddrs", za0001, za0002)
						return
					}
					if cap(z.NetAddrs[za0001][za0002]) >= int(zb0004) {
						z.NetAddrs[za0001][za0002] = (z.NetAddrs[za0001][za0002])[:zb0004]
					} else {
						z.NetAddrs[za0001][za0002] = make([]uint16, zb0004)
					}
					for za0003 := range z.NetAddrs[za0001][za0002] {
						z.NetAddrs[za0001][za0002][za0003], err = dc.ReadUint16()
						if err != nil {
							err = msgp.WrapError(err, "NetAddrs", za0001, za0002, za0003)
							return
						}
					}
				}
			}
		case "masks":
			var zb0005 uint32
			zb0005, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "NetMasks")
				return
			}
			if zb0005 != uint32(256) {
				err = msgp.ArrayError{Wanted: uint32(256), Got: zb0005}
				return
			}
			for za0004 := range z.NetMasks {
				var zb0006 uint32
				zb0006, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "NetMasks", za0004)
					return
				}
				if zb0006 != uint32(256) {
					err = msgp.ArrayError{Wanted: uint32(256), Got: zb0006}
					return
				}
				for za0005 := range z.NetMasks[za0004] {
					var zb0007 uint32
					zb0007, err = dc.ReadArrayHeader()
					if err != nil {
						err = msgp.WrapError(err, "NetMasks", za0004, za0005)
						return
					}
					if cap(z.NetMasks[za0004][za0005]) >= int(zb0007) {
						z.NetMasks[za0004][za0005] = (z.NetMasks[za0004][za0005])[:zb0007]
					} else {
						z.NetMasks[za0004][za0005] = make([]uint8, zb0007)
					}
					for za0006 := range z.NetMasks[za0004][za0005] {
						z.NetMasks[za0004][za0005][za0006], err = dc.ReadUint8()
						if err != nil {
							err = msgp.WrapError(err, "NetMasks", za0004, za0005, za0006)
							return
						}
					}
				}
			}
		case "geo_ids":
			var zb0008 uint32
			zb0008, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "GeoIDs")
				return
			}
			if zb0008 != uint32(256) {
				err = msgp.ArrayError{Wanted: uint32(256), Got: zb0008}
				return
			}
			for za0007 := range z.GeoIDs {
				var zb0009 uint32
				zb0009, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "GeoIDs", za0007)
					return
				}
				if zb0009 != uint32(256) {
					err = msgp.ArrayError{Wanted: uint32(256), Got: zb0009}
					return
				}
				for za0008 := range z.GeoIDs[za0007] {
					var zb0010 uint32
					zb0010, err = dc.ReadArrayHeader()
					if err != nil {
						err = msgp.WrapError(err, "GeoIDs", za0007, za0008)
						return
					}
					if cap(z.GeoIDs[za0007][za0008]) >= int(zb0010) {
						z.GeoIDs[za0007][za0008] = (z.GeoIDs[za0007][za0008])[:zb0010]
					} else {
						z.GeoIDs[za0007][za0008] = make([]uint32, zb0010)
					}
					for za0009 := range z.GeoIDs[za0007][za0008] {
						z.GeoIDs[za0007][za0008][za0009], err = dc.ReadUint32()
						if err != nil {
							err = msgp.WrapError(err, "GeoIDs", za0007, za0008, za0009)
							return
						}
					}
				}
			}
		case "geos":
			var zb0011 uint32
			zb0011, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Geos")
				return
			}
			if cap(z.Geos) >= int(zb0011) {
				z.Geos = (z.Geos)[:zb0011]
			} else {
				z.Geos = make([]*Geo, zb0011)
			}
			for za0010 := range z.Geos {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "Geos", za0010)
						return
					}
					z.Geos[za0010] = nil
				} else {
					if z.Geos[za0010] == nil {
						z.Geos[za0010] = new(Geo)
					}
					err = z.Geos[za0010].DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Geos", za0010)
						return
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *DBDump) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "adds"
	err = en.Append(0x84, 0xa4, 0x61, 0x64, 0x64, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(256))
	if err != nil {
		err = msgp.WrapError(err, "NetAddrs")
		return
	}
	for za0001 := range z.NetAddrs {
		err = en.WriteArrayHeader(uint32(256))
		if err != nil {
			err = msgp.WrapError(err, "NetAddrs", za0001)
			return
		}
		for za0002 := range z.NetAddrs[za0001] {
			err = en.WriteArrayHeader(uint32(len(z.NetAddrs[za0001][za0002])))
			if err != nil {
				err = msgp.WrapError(err, "NetAddrs", za0001, za0002)
				return
			}
			for za0003 := range z.NetAddrs[za0001][za0002] {
				err = en.WriteUint16(z.NetAddrs[za0001][za0002][za0003])
				if err != nil {
					err = msgp.WrapError(err, "NetAddrs", za0001, za0002, za0003)
					return
				}
			}
		}
	}
	// write "masks"
	err = en.Append(0xa5, 0x6d, 0x61, 0x73, 0x6b, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(256))
	if err != nil {
		err = msgp.WrapError(err, "NetMasks")
		return
	}
	for za0004 := range z.NetMasks {
		err = en.WriteArrayHeader(uint32(256))
		if err != nil {
			err = msgp.WrapError(err, "NetMasks", za0004)
			return
		}
		for za0005 := range z.NetMasks[za0004] {
			err = en.WriteArrayHeader(uint32(len(z.NetMasks[za0004][za0005])))
			if err != nil {
				err = msgp.WrapError(err, "NetMasks", za0004, za0005)
				return
			}
			for za0006 := range z.NetMasks[za0004][za0005] {
				err = en.WriteUint8(z.NetMasks[za0004][za0005][za0006])
				if err != nil {
					err = msgp.WrapError(err, "NetMasks", za0004, za0005, za0006)
					return
				}
			}
		}
	}
	// write "geo_ids"
	err = en.Append(0xa7, 0x67, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(256))
	if err != nil {
		err = msgp.WrapError(err, "GeoIDs")
		return
	}
	for za0007 := range z.GeoIDs {
		err = en.WriteArrayHeader(uint32(256))
		if err != nil {
			err = msgp.WrapError(err, "GeoIDs", za0007)
			return
		}
		for za0008 := range z.GeoIDs[za0007] {
			err = en.WriteArrayHeader(uint32(len(z.GeoIDs[za0007][za0008])))
			if err != nil {
				err = msgp.WrapError(err, "GeoIDs", za0007, za0008)
				return
			}
			for za0009 := range z.GeoIDs[za0007][za0008] {
				err = en.WriteUint32(z.GeoIDs[za0007][za0008][za0009])
				if err != nil {
					err = msgp.WrapError(err, "GeoIDs", za0007, za0008, za0009)
					return
				}
			}
		}
	}
	// write "geos"
	err = en.Append(0xa4, 0x67, 0x65, 0x6f, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Geos)))
	if err != nil {
		err = msgp.WrapError(err, "Geos")
		return
	}
	for za0010 := range z.Geos {
		if z.Geos[za0010] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.Geos[za0010].EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Geos", za0010)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *DBDump) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "adds"
	o = append(o, 0x84, 0xa4, 0x61, 0x64, 0x64, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(256))
	for za0001 := range z.NetAddrs {
		o = msgp.AppendArrayHeader(o, uint32(256))
		for za0002 := range z.NetAddrs[za0001] {
			o = msgp.AppendArrayHeader(o, uint32(len(z.NetAddrs[za0001][za0002])))
			for za0003 := range z.NetAddrs[za0001][za0002] {
				o = msgp.AppendUint16(o, z.NetAddrs[za0001][za0002][za0003])
			}
		}
	}
	// string "masks"
	o = append(o, 0xa5, 0x6d, 0x61, 0x73, 0x6b, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(256))
	for za0004 := range z.NetMasks {
		o = msgp.AppendArrayHeader(o, uint32(256))
		for za0005 := range z.NetMasks[za0004] {
			o = msgp.AppendArrayHeader(o, uint32(len(z.NetMasks[za0004][za0005])))
			for za0006 := range z.NetMasks[za0004][za0005] {
				o = msgp.AppendUint8(o, z.NetMasks[za0004][za0005][za0006])
			}
		}
	}
	// string "geo_ids"
	o = append(o, 0xa7, 0x67, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(256))
	for za0007 := range z.GeoIDs {
		o = msgp.AppendArrayHeader(o, uint32(256))
		for za0008 := range z.GeoIDs[za0007] {
			o = msgp.AppendArrayHeader(o, uint32(len(z.GeoIDs[za0007][za0008])))
			for za0009 := range z.GeoIDs[za0007][za0008] {
				o = msgp.AppendUint32(o, z.GeoIDs[za0007][za0008][za0009])
			}
		}
	}
	// string "geos"
	o = append(o, 0xa4, 0x67, 0x65, 0x6f, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Geos)))
	for za0010 := range z.Geos {
		if z.Geos[za0010] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z.Geos[za0010].MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "Geos", za0010)
				return
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *DBDump) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "adds":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NetAddrs")
				return
			}
			if zb0002 != uint32(256) {
				err = msgp.ArrayError{Wanted: uint32(256), Got: zb0002}
				return
			}
			for za0001 := range z.NetAddrs {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "NetAddrs", za0001)
					return
				}
				if zb0003 != uint32(256) {
					err = msgp.ArrayError{Wanted: uint32(256), Got: zb0003}
					return
				}
				for za0002 := range z.NetAddrs[za0001] {
					var zb0004 uint32
					zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "NetAddrs", za0001, za0002)
						return
					}
					if cap(z.NetAddrs[za0001][za0002]) >= int(zb0004) {
						z.NetAddrs[za0001][za0002] = (z.NetAddrs[za0001][za0002])[:zb0004]
					} else {
						z.NetAddrs[za0001][za0002] = make([]uint16, zb0004)
					}
					for za0003 := range z.NetAddrs[za0001][za0002] {
						z.NetAddrs[za0001][za0002][za0003], bts, err = msgp.ReadUint16Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "NetAddrs", za0001, za0002, za0003)
							return
						}
					}
				}
			}
		case "masks":
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NetMasks")
				return
			}
			if zb0005 != uint32(256) {
				err = msgp.ArrayError{Wanted: uint32(256), Got: zb0005}
				return
			}
			for za0004 := range z.NetMasks {
				var zb0006 uint32
				zb0006, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "NetMasks", za0004)
					return
				}
				if zb0006 != uint32(256) {
					err = msgp.ArrayError{Wanted: uint32(256), Got: zb0006}
					return
				}
				for za0005 := range z.NetMasks[za0004] {
					var zb0007 uint32
					zb0007, bts, err = msgp.ReadArrayHeaderBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "NetMasks", za0004, za0005)
						return
					}
					if cap(z.NetMasks[za0004][za0005]) >= int(zb0007) {
						z.NetMasks[za0004][za0005] = (z.NetMasks[za0004][za0005])[:zb0007]
					} else {
						z.NetMasks[za0004][za0005] = make([]uint8, zb0007)
					}
					for za0006 := range z.NetMasks[za0004][za0005] {
						z.NetMasks[za0004][za0005][za0006], bts, err = msgp.ReadUint8Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "NetMasks", za0004, za0005, za0006)
							return
						}
					}
				}
			}
		case "geo_ids":
			var zb0008 uint32
			zb0008, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "GeoIDs")
				return
			}
			if zb0008 != uint32(256) {
				err = msgp.ArrayError{Wanted: uint32(256), Got: zb0008}
				return
			}
			for za0007 := range z.GeoIDs {
				var zb0009 uint32
				zb0009, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "GeoIDs", za0007)
					return
				}
				if zb0009 != uint32(256) {
					err = msgp.ArrayError{Wanted: uint32(256), Got: zb0009}
					return
				}
				for za0008 := range z.GeoIDs[za0007] {
					var zb0010 uint32
					zb0010, bts, err = msgp.ReadArrayHeaderBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "GeoIDs", za0007, za0008)
						return
					}
					if cap(z.GeoIDs[za0007][za0008]) >= int(zb0010) {
						z.GeoIDs[za0007][za0008] = (z.GeoIDs[za0007][za0008])[:zb0010]
					} else {
						z.GeoIDs[za0007][za0008] = make([]uint32, zb0010)
					}
					for za0009 := range z.GeoIDs[za0007][za0008] {
						z.GeoIDs[za0007][za0008][za0009], bts, err = msgp.ReadUint32Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "GeoIDs", za0007, za0008, za0009)
							return
						}
					}
				}
			}
		case "geos":
			var zb0011 uint32
			zb0011, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Geos")
				return
			}
			if cap(z.Geos) >= int(zb0011) {
				z.Geos = (z.Geos)[:zb0011]
			} else {
				z.Geos = make([]*Geo, zb0011)
			}
			for za0010 := range z.Geos {
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					z.Geos[za0010] = nil
				} else {
					if z.Geos[za0010] == nil {
						z.Geos[za0010] = new(Geo)
					}
					bts, err = z.Geos[za0010].UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Geos", za0010)
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *DBDump) Msgsize() (s int) {
	s = 1 + 5 + msgp.ArrayHeaderSize
	for za0001 := range z.NetAddrs {
		s += msgp.ArrayHeaderSize
		for za0002 := range z.NetAddrs[za0001] {
			s += msgp.ArrayHeaderSize + (len(z.NetAddrs[za0001][za0002]) * (msgp.Uint16Size))
		}
	}
	s += 6 + msgp.ArrayHeaderSize
	for za0004 := range z.NetMasks {
		s += msgp.ArrayHeaderSize
		for za0005 := range z.NetMasks[za0004] {
			s += msgp.ArrayHeaderSize + (len(z.NetMasks[za0004][za0005]) * (msgp.Uint8Size))
		}
	}
	s += 8 + msgp.ArrayHeaderSize
	for za0007 := range z.GeoIDs {
		s += msgp.ArrayHeaderSize
		for za0008 := range z.GeoIDs[za0007] {
			s += msgp.ArrayHeaderSize + (len(z.GeoIDs[za0007][za0008]) * (msgp.Uint32Size))
		}
	}
	s += 5 + msgp.ArrayHeaderSize
	for za0010 := range z.Geos {
		if z.Geos[za0010] == nil {
			s += msgp.NilSize
		} else {
			s += z.Geos[za0010].Msgsize()
		}
	}
	return
}
