package birdwatcher

type Country [2]byte

func (c Country) MarshalText() ([]byte, error) {
	return []byte(c.String()), nil
}

func (c Country) String() string {
	if name, ok := countries[c]; ok {
		return name
	}

	return "N/A"
}

var countries = map[Country]string{
	Country{'A', 'F'}: "Afghanistan",
	Country{'A', 'L'}: "Albania",
	Country{'D', 'Z'}: "Algeria",
	Country{'A', 'S'}: "American Samoa",
	Country{'A', 'D'}: "Andorra",
	Country{'A', 'O'}: "Angola",
	Country{'A', 'I'}: "Anguilla",
	Country{'A', 'Q'}: "Antarctica",
	Country{'A', 'G'}: "Antigua and Barbuda",
	Country{'A', 'R'}: "Argentina",
	Country{'A', 'M'}: "Armenia",
	Country{'A', 'W'}: "Aruba",
	Country{'A', 'U'}: "Australia",
	Country{'A', 'T'}: "Austria",
	Country{'A', 'Z'}: "Azerbaijan",
	Country{'B', 'S'}: "Bahamas",
	Country{'B', 'H'}: "Bahrain",
	Country{'B', 'D'}: "Bangladesh",
	Country{'B', 'B'}: "Barbados",
	Country{'B', 'Y'}: "Belarus",
	Country{'B', 'E'}: "Belgium",
	Country{'B', 'Z'}: "Belize",
	Country{'B', 'J'}: "Benin",
	Country{'B', 'M'}: "Bermuda",
	Country{'B', 'T'}: "Bhutan",
	Country{'B', 'O'}: "Bolivia",
	Country{'B', 'Q'}: "Bonaire, Sint Eustatius and Saba",
	Country{'B', 'A'}: "Bosnia and Herzegovina",
	Country{'B', 'W'}: "Botswana",
	Country{'B', 'V'}: "Bouvet Island",
	Country{'B', 'R'}: "Brazil",
	Country{'I', 'O'}: "British Indian Ocean Territory",
	Country{'B', 'N'}: "Brunei Darussalam",
	Country{'B', 'G'}: "Bulgaria",
	Country{'B', 'F'}: "Burkina Faso",
	Country{'B', 'I'}: "Burundi",
	Country{'C', 'V'}: "Cabo Verde",
	Country{'K', 'H'}: "Cambodia",
	Country{'C', 'M'}: "Cameroon",
	Country{'C', 'A'}: "Canada",
	Country{'K', 'Y'}: "Cayman Islands",
	Country{'C', 'F'}: "Central African Republic",
	Country{'T', 'D'}: "Chad",
	Country{'C', 'L'}: "Chile",
	Country{'C', 'N'}: "China",
	Country{'C', 'X'}: "Christmas Island",
	Country{'C', 'C'}: "Cocos Islands",
	Country{'C', 'O'}: "Colombia",
	Country{'K', 'M'}: "Comoros",
	Country{'C', 'D'}: "Democratic Republic of the Congo",
	Country{'C', 'G'}: "Republic of the Congo",
	Country{'C', 'K'}: "Cook Islands",
	Country{'C', 'R'}: "Costa Rica",
	Country{'H', 'R'}: "Croatia",
	Country{'C', 'U'}: "Cuba",
	Country{'C', 'W'}: "Curaçao",
	Country{'C', 'Y'}: "Cyprus",
	Country{'C', 'Z'}: "Czechia",
	Country{'C', 'I'}: "Côte d'Ivoire",
	Country{'D', 'K'}: "Denmark",
	Country{'D', 'J'}: "Djibouti",
	Country{'D', 'M'}: "Dominica",
	Country{'D', 'O'}: "Dominican Republic",
	Country{'E', 'C'}: "Ecuador",
	Country{'E', 'G'}: "Egypt",
	Country{'S', 'V'}: "El Salvador",
	Country{'G', 'Q'}: "Equatorial Guinea",
	Country{'E', 'R'}: "Eritrea",
	Country{'E', 'E'}: "Estonia",
	Country{'S', 'Z'}: "Eswatini",
	Country{'E', 'T'}: "Ethiopia",
	Country{'F', 'K'}: "Falkland Islands",
	Country{'F', 'O'}: "Faroe Islands",
	Country{'F', 'J'}: "Fiji",
	Country{'F', 'I'}: "Finland",
	Country{'F', 'R'}: "France",
	Country{'G', 'F'}: "French Guiana",
	Country{'P', 'F'}: "French Polynesia",
	Country{'T', 'F'}: "French Southern Territories",
	Country{'G', 'A'}: "Gabon",
	Country{'G', 'M'}: "Gambia",
	Country{'G', 'E'}: "Georgia",
	Country{'D', 'E'}: "Germany",
	Country{'G', 'H'}: "Ghana",
	Country{'G', 'I'}: "Gibraltar",
	Country{'G', 'R'}: "Greece",
	Country{'G', 'L'}: "Greenland",
	Country{'G', 'D'}: "Grenada",
	Country{'G', 'P'}: "Guadeloupe",
	Country{'G', 'U'}: "Guam",
	Country{'G', 'T'}: "Guatemala",
	Country{'G', 'G'}: "Guernsey",
	Country{'G', 'N'}: "Guinea",
	Country{'G', 'W'}: "Guinea-Bissau",
	Country{'G', 'Y'}: "Guyana",
	Country{'H', 'T'}: "Haiti",
	Country{'H', 'M'}: "Heard Island and McDonald Islands",
	Country{'V', 'A'}: "Holy See",
	Country{'H', 'N'}: "Honduras",
	Country{'H', 'K'}: "Hong Kong",
	Country{'H', 'U'}: "Hungary",
	Country{'I', 'S'}: "Iceland",
	Country{'I', 'N'}: "India",
	Country{'I', 'D'}: "Indonesia",
	Country{'I', 'R'}: "Iran",
	Country{'I', 'Q'}: "Iraq",
	Country{'I', 'E'}: "Ireland",
	Country{'I', 'M'}: "Isle of Man",
	Country{'I', 'L'}: "Israel",
	Country{'I', 'T'}: "Italy",
	Country{'J', 'M'}: "Jamaica",
	Country{'J', 'P'}: "Japan",
	Country{'J', 'E'}: "Jersey",
	Country{'J', 'O'}: "Jordan",
	Country{'K', 'Z'}: "Kazakhstan",
	Country{'K', 'E'}: "Kenya",
	Country{'K', 'I'}: "Kiribati",
	Country{'K', 'P'}: "North Korea",
	Country{'K', 'R'}: "Republic of Korea",
	Country{'K', 'W'}: "Kuwait",
	Country{'K', 'G'}: "Kyrgyzstan",
	Country{'L', 'A'}: "Lao People's Democratic Republic",
	Country{'L', 'V'}: "Latvia",
	Country{'L', 'B'}: "Lebanon",
	Country{'L', 'S'}: "Lesotho",
	Country{'L', 'R'}: "Liberia",
	Country{'L', 'Y'}: "Libya",
	Country{'L', 'I'}: "Liechtenstein",
	Country{'L', 'T'}: "Lithuania",
	Country{'L', 'U'}: "Luxembourg",
	Country{'M', 'O'}: "Macao",
	Country{'M', 'G'}: "Madagascar",
	Country{'M', 'W'}: "Malawi",
	Country{'M', 'Y'}: "Malaysia",
	Country{'M', 'V'}: "Maldives",
	Country{'M', 'L'}: "Mali",
	Country{'M', 'T'}: "Malta",
	Country{'M', 'H'}: "Marshall Islands",
	Country{'M', 'Q'}: "Martinique",
	Country{'M', 'R'}: "Mauritania",
	Country{'M', 'U'}: "Mauritius",
	Country{'Y', 'T'}: "Mayotte",
	Country{'M', 'X'}: "Mexico",
	Country{'F', 'M'}: "Micronesia",
	Country{'M', 'D'}: "Moldova",
	Country{'M', 'C'}: "Monaco",
	Country{'M', 'N'}: "Mongolia",
	Country{'M', 'E'}: "Montenegro",
	Country{'M', 'S'}: "Montserrat",
	Country{'M', 'A'}: "Morocco",
	Country{'M', 'Z'}: "Mozambique",
	Country{'M', 'M'}: "Myanmar",
	Country{'N', 'A'}: "Namibia",
	Country{'N', 'R'}: "Nauru",
	Country{'N', 'P'}: "Nepal",
	Country{'N', 'L'}: "Netherlands",
	Country{'N', 'C'}: "New Caledonia",
	Country{'N', 'Z'}: "New Zealand",
	Country{'N', 'I'}: "Nicaragua",
	Country{'N', 'E'}: "Niger",
	Country{'N', 'G'}: "Nigeria",
	Country{'N', 'U'}: "Niue",
	Country{'N', 'F'}: "Norfolk Island",
	Country{'M', 'P'}: "Northern Mariana Islands",
	Country{'N', 'O'}: "Norway",
	Country{'O', 'M'}: "Oman",
	Country{'P', 'K'}: "Pakistan",
	Country{'P', 'W'}: "Palau",
	Country{'P', 'S'}: "Palestine, State of",
	Country{'P', 'A'}: "Panama",
	Country{'P', 'G'}: "Papua New Guinea",
	Country{'P', 'Y'}: "Paraguay",
	Country{'P', 'E'}: "Peru",
	Country{'P', 'H'}: "Philippines",
	Country{'P', 'N'}: "Pitcairn",
	Country{'P', 'L'}: "Poland",
	Country{'P', 'T'}: "Portugal",
	Country{'P', 'R'}: "Puerto Rico",
	Country{'Q', 'A'}: "Qatar",
	Country{'M', 'K'}: "Republic of North Macedonia",
	Country{'R', 'O'}: "Romania",
	Country{'R', 'U'}: "Russian Federation",
	Country{'R', 'W'}: "Rwanda",
	Country{'R', 'E'}: "Réunion",
	Country{'B', 'L'}: "Saint Barthélemy",
	Country{'S', 'H'}: "Saint Helena, Ascension and Tristan da Cunha",
	Country{'K', 'N'}: "Saint Kitts and Nevis",
	Country{'L', 'C'}: "Saint Lucia",
	Country{'M', 'F'}: "Saint Martin (French part)",
	Country{'P', 'M'}: "Saint Pierre and Miquelon",
	Country{'V', 'C'}: "Saint Vincent and the Grenadines",
	Country{'W', 'S'}: "Samoa",
	Country{'S', 'M'}: "San Marino",
	Country{'S', 'T'}: "Sao Tome and Principe",
	Country{'S', 'A'}: "Saudi Arabia",
	Country{'S', 'N'}: "Senegal",
	Country{'R', 'S'}: "Serbia",
	Country{'S', 'C'}: "Seychelles",
	Country{'S', 'L'}: "Sierra Leone",
	Country{'S', 'G'}: "Singapore",
	Country{'S', 'X'}: "Sint Maarten (Dutch part)",
	Country{'S', 'K'}: "Slovakia",
	Country{'S', 'I'}: "Slovenia",
	Country{'S', 'B'}: "Solomon Islands",
	Country{'S', 'O'}: "Somalia",
	Country{'Z', 'A'}: "South Africa",
	Country{'G', 'S'}: "South Georgia and the South Sandwich Islands",
	Country{'S', 'S'}: "South Sudan",
	Country{'E', 'S'}: "Spain",
	Country{'L', 'K'}: "Sri Lanka",
	Country{'S', 'D'}: "Sudan",
	Country{'S', 'R'}: "Suriname",
	Country{'S', 'J'}: "Svalbard and Jan Mayen",
	Country{'S', 'E'}: "Sweden",
	Country{'C', 'H'}: "Switzerland",
	Country{'S', 'Y'}: "Syrian Arab Republic",
	Country{'T', 'W'}: "Taiwan",
	Country{'T', 'J'}: "Tajikistan",
	Country{'T', 'Z'}: "Tanzania",
	Country{'T', 'H'}: "Thailand",
	Country{'T', 'L'}: "Timor-Leste",
	Country{'T', 'G'}: "Togo",
	Country{'T', 'K'}: "Tokelau",
	Country{'T', 'O'}: "Tonga",
	Country{'T', 'T'}: "Trinidad and Tobago",
	Country{'T', 'N'}: "Tunisia",
	Country{'T', 'R'}: "Turkey",
	Country{'T', 'M'}: "Turkmenistan",
	Country{'T', 'C'}: "Turks and Caicos Islands",
	Country{'T', 'V'}: "Tuvalu",
	Country{'U', 'G'}: "Uganda",
	Country{'U', 'A'}: "Ukraine",
	Country{'A', 'E'}: "United Arab Emirates",
	Country{'G', 'B'}: "United Kingdom",
	Country{'U', 'M'}: "United States Minor Outlying Islands",
	Country{'U', 'S'}: "United States of America",
	Country{'U', 'Y'}: "Uruguay",
	Country{'U', 'Z'}: "Uzbekistan",
	Country{'V', 'U'}: "Vanuatu",
	Country{'V', 'E'}: "Venezuela",
	Country{'V', 'N'}: "Viet Nam",
	Country{'V', 'G'}: "Virgin Islands (British)",
	Country{'V', 'I'}: "Virgin Islands (U.S.)",
	Country{'W', 'F'}: "Wallis and Futuna",
	Country{'E', 'H'}: "Western Sahara",
	Country{'Y', 'E'}: "Yemen",
	Country{'Z', 'M'}: "Zambia",
	Country{'Z', 'W'}: "Zimbabwe",
	Country{'A', 'X'}: "Åland Islands",
}
