package birdwatcher

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Geo) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 4 {
		err = msgp.ArrayError{Wanted: 4, Got: zb0001}
		return
	}
	z.City, err = dc.ReadString()
	if err != nil {
		err = msgp.WrapError(err, "City")
		return
	}
	z.Region, err = dc.ReadString()
	if err != nil {
		err = msgp.WrapError(err, "Region")
		return
	}
	err = dc.ReadExactBytes((z.Country)[:])
	if err != nil {
		err = msgp.WrapError(err, "Country")
		return
	}
	z.IsEU, err = dc.ReadBool()
	if err != nil {
		err = msgp.WrapError(err, "IsEU")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Geo) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 4
	err = en.Append(0x94)
	if err != nil {
		return
	}
	err = en.WriteString(z.City)
	if err != nil {
		err = msgp.WrapError(err, "City")
		return
	}
	err = en.WriteString(z.Region)
	if err != nil {
		err = msgp.WrapError(err, "Region")
		return
	}
	err = en.WriteBytes((z.Country)[:])
	if err != nil {
		err = msgp.WrapError(err, "Country")
		return
	}
	err = en.WriteBool(z.IsEU)
	if err != nil {
		err = msgp.WrapError(err, "IsEU")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Geo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 4
	o = append(o, 0x94)
	o = msgp.AppendString(o, z.City)
	o = msgp.AppendString(o, z.Region)
	o = msgp.AppendBytes(o, (z.Country)[:])
	o = msgp.AppendBool(o, z.IsEU)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Geo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 4 {
		err = msgp.ArrayError{Wanted: 4, Got: zb0001}
		return
	}
	z.City, bts, err = msgp.ReadStringBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "City")
		return
	}
	z.Region, bts, err = msgp.ReadStringBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Region")
		return
	}
	bts, err = msgp.ReadExactBytes(bts, (z.Country)[:])
	if err != nil {
		err = msgp.WrapError(err, "Country")
		return
	}
	z.IsEU, bts, err = msgp.ReadBoolBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "IsEU")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Geo) Msgsize() (s int) {
	s = 1 + msgp.StringPrefixSize + len(z.City) + msgp.StringPrefixSize + len(z.Region) + msgp.ArrayHeaderSize + (2 * (msgp.ByteSize)) + msgp.BoolSize
	return
}
