package birdwatcher

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *DBDump) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "adds":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "NetAddrs")
				return
			}
			if cap(z.NetAddrs) >= int(zb0002) {
				z.NetAddrs = (z.NetAddrs)[:zb0002]
			} else {
				z.NetAddrs = make([]simpleIP, zb0002)
			}
			for za0002 := range z.NetAddrs {
				{
					var zb0003 uint32
					zb0003, err = dc.ReadUint32()
					if err != nil {
						err = msgp.WrapError(err, "NetAddrs", za0002)
						return
					}
					z.NetAddrs[za0002] = simpleIP(zb0003)
				}
			}
		case "masks":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "NetMasks")
				return
			}
			if cap(z.NetMasks) >= int(zb0004) {
				z.NetMasks = (z.NetMasks)[:zb0004]
			} else {
				z.NetMasks = make([]simpleMask, zb0004)
			}
			for za0003 := range z.NetMasks {
				{
					var zb0005 uint8
					zb0005, err = dc.ReadUint8()
					if err != nil {
						err = msgp.WrapError(err, "NetMasks", za0003)
						return
					}
					z.NetMasks[za0003] = simpleMask(zb0005)
				}
			}
		case "geo_ids":
			var zb0006 uint32
			zb0006, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "GeoIDs")
				return
			}
			if cap(z.GeoIDs) >= int(zb0006) {
				z.GeoIDs = (z.GeoIDs)[:zb0006]
			} else {
				z.GeoIDs = make([]uint32, zb0006)
			}
			for za0004 := range z.GeoIDs {
				z.GeoIDs[za0004], err = dc.ReadUint32()
				if err != nil {
					err = msgp.WrapError(err, "GeoIDs", za0004)
					return
				}
			}
		case "geos":
			var zb0007 uint32
			zb0007, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Geos")
				return
			}
			if cap(z.Geos) >= int(zb0007) {
				z.Geos = (z.Geos)[:zb0007]
			} else {
				z.Geos = make([]*Geo, zb0007)
			}
			for za0005 := range z.Geos {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "Geos", za0005)
						return
					}
					z.Geos[za0005] = nil
				} else {
					if z.Geos[za0005] == nil {
						z.Geos[za0005] = new(Geo)
					}
					err = z.Geos[za0005].DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Geos", za0005)
						return
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *DBDump) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "adds"
	err = en.Append(0x84, 0xa4, 0x61, 0x64, 0x64, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.NetAddrs)))
	if err != nil {
		err = msgp.WrapError(err, "NetAddrs")
		return
	}
	for za0002 := range z.NetAddrs {
		err = en.WriteUint32(uint32(z.NetAddrs[za0002]))
		if err != nil {
			err = msgp.WrapError(err, "NetAddrs", za0002)
			return
		}
	}
	// write "masks"
	err = en.Append(0xa5, 0x6d, 0x61, 0x73, 0x6b, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.NetMasks)))
	if err != nil {
		err = msgp.WrapError(err, "NetMasks")
		return
	}
	for za0003 := range z.NetMasks {
		err = en.WriteUint8(uint8(z.NetMasks[za0003]))
		if err != nil {
			err = msgp.WrapError(err, "NetMasks", za0003)
			return
		}
	}
	// write "geo_ids"
	err = en.Append(0xa7, 0x67, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.GeoIDs)))
	if err != nil {
		err = msgp.WrapError(err, "GeoIDs")
		return
	}
	for za0004 := range z.GeoIDs {
		err = en.WriteUint32(z.GeoIDs[za0004])
		if err != nil {
			err = msgp.WrapError(err, "GeoIDs", za0004)
			return
		}
	}
	// write "geos"
	err = en.Append(0xa4, 0x67, 0x65, 0x6f, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Geos)))
	if err != nil {
		err = msgp.WrapError(err, "Geos")
		return
	}
	for za0005 := range z.Geos {
		if z.Geos[za0005] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.Geos[za0005].EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Geos", za0005)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *DBDump) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "adds"
	o = append(o, 0x84, 0xa4, 0x61, 0x64, 0x64, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.NetAddrs)))
	for za0002 := range z.NetAddrs {
		o = msgp.AppendUint32(o, uint32(z.NetAddrs[za0002]))
	}
	// string "masks"
	o = append(o, 0xa5, 0x6d, 0x61, 0x73, 0x6b, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.NetMasks)))
	for za0003 := range z.NetMasks {
		o = msgp.AppendUint8(o, uint8(z.NetMasks[za0003]))
	}
	// string "geo_ids"
	o = append(o, 0xa7, 0x67, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.GeoIDs)))
	for za0004 := range z.GeoIDs {
		o = msgp.AppendUint32(o, z.GeoIDs[za0004])
	}
	// string "geos"
	o = append(o, 0xa4, 0x67, 0x65, 0x6f, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Geos)))
	for za0005 := range z.Geos {
		if z.Geos[za0005] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z.Geos[za0005].MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "Geos", za0005)
				return
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *DBDump) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "adds":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NetAddrs")
				return
			}
			if cap(z.NetAddrs) >= int(zb0002) {
				z.NetAddrs = (z.NetAddrs)[:zb0002]
			} else {
				z.NetAddrs = make([]simpleIP, zb0002)
			}
			for za0002 := range z.NetAddrs {
				{
					var zb0003 uint32
					zb0003, bts, err = msgp.ReadUint32Bytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "NetAddrs", za0002)
						return
					}
					z.NetAddrs[za0002] = simpleIP(zb0003)
				}
			}
		case "masks":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NetMasks")
				return
			}
			if cap(z.NetMasks) >= int(zb0004) {
				z.NetMasks = (z.NetMasks)[:zb0004]
			} else {
				z.NetMasks = make([]simpleMask, zb0004)
			}
			for za0003 := range z.NetMasks {
				{
					var zb0005 uint8
					zb0005, bts, err = msgp.ReadUint8Bytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "NetMasks", za0003)
						return
					}
					z.NetMasks[za0003] = simpleMask(zb0005)
				}
			}
		case "geo_ids":
			var zb0006 uint32
			zb0006, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "GeoIDs")
				return
			}
			if cap(z.GeoIDs) >= int(zb0006) {
				z.GeoIDs = (z.GeoIDs)[:zb0006]
			} else {
				z.GeoIDs = make([]uint32, zb0006)
			}
			for za0004 := range z.GeoIDs {
				z.GeoIDs[za0004], bts, err = msgp.ReadUint32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "GeoIDs", za0004)
					return
				}
			}
		case "geos":
			var zb0007 uint32
			zb0007, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Geos")
				return
			}
			if cap(z.Geos) >= int(zb0007) {
				z.Geos = (z.Geos)[:zb0007]
			} else {
				z.Geos = make([]*Geo, zb0007)
			}
			for za0005 := range z.Geos {
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					z.Geos[za0005] = nil
				} else {
					if z.Geos[za0005] == nil {
						z.Geos[za0005] = new(Geo)
					}
					bts, err = z.Geos[za0005].UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Geos", za0005)
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *DBDump) Msgsize() (s int) {
	s = 1 + 5 + msgp.ArrayHeaderSize + (len(z.NetAddrs) * (msgp.Uint32Size)) + 6 + msgp.ArrayHeaderSize + (len(z.NetMasks) * (msgp.Uint8Size)) + 8 + msgp.ArrayHeaderSize + (len(z.GeoIDs) * (msgp.Uint32Size)) + 5 + msgp.ArrayHeaderSize
	for za0005 := range z.Geos {
		if z.Geos[za0005] == nil {
			s += msgp.NilSize
		} else {
			s += z.Geos[za0005].Msgsize()
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Geo) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 4 {
		err = msgp.ArrayError{Wanted: 4, Got: zb0001}
		return
	}
	z.City, err = dc.ReadString()
	if err != nil {
		err = msgp.WrapError(err, "City")
		return
	}
	z.Region, err = dc.ReadString()
	if err != nil {
		err = msgp.WrapError(err, "Region")
		return
	}
	err = dc.ReadExactBytes((z.Country)[:])
	if err != nil {
		err = msgp.WrapError(err, "Country")
		return
	}
	z.IsEU, err = dc.ReadBool()
	if err != nil {
		err = msgp.WrapError(err, "IsEU")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Geo) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 4
	err = en.Append(0x94)
	if err != nil {
		return
	}
	err = en.WriteString(z.City)
	if err != nil {
		err = msgp.WrapError(err, "City")
		return
	}
	err = en.WriteString(z.Region)
	if err != nil {
		err = msgp.WrapError(err, "Region")
		return
	}
	err = en.WriteBytes((z.Country)[:])
	if err != nil {
		err = msgp.WrapError(err, "Country")
		return
	}
	err = en.WriteBool(z.IsEU)
	if err != nil {
		err = msgp.WrapError(err, "IsEU")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Geo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 4
	o = append(o, 0x94)
	o = msgp.AppendString(o, z.City)
	o = msgp.AppendString(o, z.Region)
	o = msgp.AppendBytes(o, (z.Country)[:])
	o = msgp.AppendBool(o, z.IsEU)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Geo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 4 {
		err = msgp.ArrayError{Wanted: 4, Got: zb0001}
		return
	}
	z.City, bts, err = msgp.ReadStringBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "City")
		return
	}
	z.Region, bts, err = msgp.ReadStringBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Region")
		return
	}
	bts, err = msgp.ReadExactBytes(bts, (z.Country)[:])
	if err != nil {
		err = msgp.WrapError(err, "Country")
		return
	}
	z.IsEU, bts, err = msgp.ReadBoolBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "IsEU")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Geo) Msgsize() (s int) {
	s = 1 + msgp.StringPrefixSize + len(z.City) + msgp.StringPrefixSize + len(z.Region) + msgp.ArrayHeaderSize + (2 * (msgp.ByteSize)) + msgp.BoolSize
	return
}
